spring.application.name=sepagateway

#database
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DB_PORT:5432}/${DATABASE_NAME:sepa-gateway-db}
spring.datasource.username=${DATABASE_USER:admin}
spring.datasource.password=${DATABASE_PASSWORD:admin}

##hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.root=DEBUG

